add_executable(vclient
    "${CMAKE_CURRENT_LIST_DIR}/net/bother.cc"
    "${CMAKE_CURRENT_LIST_DIR}/net/bother.hh"
    "${CMAKE_CURRENT_LIST_DIR}/net/host.cc"
    "${CMAKE_CURRENT_LIST_DIR}/net/host.hh"
    "${CMAKE_CURRENT_LIST_DIR}/net/session.cc"
    "${CMAKE_CURRENT_LIST_DIR}/net/session.hh"
    "${CMAKE_CURRENT_LIST_DIR}/system/interpolation.cc"
    "${CMAKE_CURRENT_LIST_DIR}/system/interpolation.hh"
    "${CMAKE_CURRENT_LIST_DIR}/system/player_look.cc"
    "${CMAKE_CURRENT_LIST_DIR}/system/player_look.hh"
    "${CMAKE_CURRENT_LIST_DIR}/system/player_move.cc"
    "${CMAKE_CURRENT_LIST_DIR}/system/player_move.hh"
    "${CMAKE_CURRENT_LIST_DIR}/system/player_target.cc"
    "${CMAKE_CURRENT_LIST_DIR}/system/player_target.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/background.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/background.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/button.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/button.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/checkbox.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/checkbox.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/container.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/dimmer.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/dimmer.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/input.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/input.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/keybind.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/keybind.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/label.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/label.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/language_selector.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/language_selector.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/list_box.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/list_box.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/menu.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/menu.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/panel.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/panel.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/popup.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/popup.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/screen.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/screen.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/scroller.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/scroller.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/separator.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/separator.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/setting.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/setting.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/slider.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/slider.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/stack.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/stack.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/stepper.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/stepper.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/tabs.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/tabs.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/title.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/title.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/toggle_button.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/toggle_button.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/video_selector.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/video_selector.hh"
    "${CMAKE_CURRENT_LIST_DIR}/gui/widget.cc"
    "${CMAKE_CURRENT_LIST_DIR}/gui/widget.hh"
    "${CMAKE_CURRENT_LIST_DIR}/res/texture2D.cc"
    "${CMAKE_CURRENT_LIST_DIR}/res/texture2D.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/biome_cache.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/biome_cache.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/block_atlas.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/block_atlas.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/block_cache.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/block_cache.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/bmodel_cache.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/bmodel_cache.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/chunk_mesh.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/chunk_mesh.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/chunk_mesher.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/chunk_mesher.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/chunk_renderer.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/chunk_renderer.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/chunk_vbo.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/chunk_vbo.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/fluid_cache.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/fluid_cache.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/outline.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/outline.hh"
    "${CMAKE_CURRENT_LIST_DIR}/world/skybox.cc"
    "${CMAKE_CURRENT_LIST_DIR}/world/skybox.hh"
    "${CMAKE_CURRENT_LIST_DIR}/camera.cc"
    "${CMAKE_CURRENT_LIST_DIR}/camera.hh"
    "${CMAKE_CURRENT_LIST_DIR}/constant.hh"
    "${CMAKE_CURRENT_LIST_DIR}/fog.cc"
    "${CMAKE_CURRENT_LIST_DIR}/fog.hh"
    "${CMAKE_CURRENT_LIST_DIR}/fonts.cc"
    "${CMAKE_CURRENT_LIST_DIR}/fonts.hh"
    "${CMAKE_CURRENT_LIST_DIR}/game.cc"
    "${CMAKE_CURRENT_LIST_DIR}/game.hh"
    "${CMAKE_CURRENT_LIST_DIR}/globals.cc"
    "${CMAKE_CURRENT_LIST_DIR}/globals.hh"
    "${CMAKE_CURRENT_LIST_DIR}/head.cc"
    "${CMAKE_CURRENT_LIST_DIR}/head.hh"
    "${CMAKE_CURRENT_LIST_DIR}/language.cc"
    "${CMAKE_CURRENT_LIST_DIR}/language.hh"
    "${CMAKE_CURRENT_LIST_DIR}/main_menu.cc"
    "${CMAKE_CURRENT_LIST_DIR}/main_menu.hh"
    "${CMAKE_CURRENT_LIST_DIR}/main.cc"
    "${CMAKE_CURRENT_LIST_DIR}/pch.hh"
    "${CMAKE_CURRENT_LIST_DIR}/play_menu.cc"
    "${CMAKE_CURRENT_LIST_DIR}/play_menu.hh"
    "${CMAKE_CURRENT_LIST_DIR}/settings.cc"
    "${CMAKE_CURRENT_LIST_DIR}/settings.hh"
    "${CMAKE_CURRENT_LIST_DIR}/shader_program.cc"
    "${CMAKE_CURRENT_LIST_DIR}/shader_program.hh"
    "${CMAKE_CURRENT_LIST_DIR}/style.cc"
    "${CMAKE_CURRENT_LIST_DIR}/style.hh"
    "${CMAKE_CURRENT_LIST_DIR}/video.cc"
    "${CMAKE_CURRENT_LIST_DIR}/video.hh")
target_compile_features(vclient PUBLIC cxx_std_20)
target_include_directories(vclient PUBLIC "${PROJECT_SOURCE_DIR}")
target_link_libraries(vclient PUBLIC core shared)
target_link_libraries(vclient PUBLIC
    deps::imgui
    deps::imgui-backend-sdl3
    deps::imgui-backend-opengl3
    deps::SDL3
    deps::glad)
target_precompile_headers(vclient PRIVATE "${CMAKE_CURRENT_LIST_DIR}/pch.hh")

install(TARGETS vclient RUNTIME DESTINATION ".")
